### ISSUE TITLE
ulauncher spotify extension crashed

### ISSUE THREAD

**Issue by atulgv** [the-lay/ulauncher-spotify-api#26]
the extension crashed
what should i do

**Comment by the-lay** [comment]
Hi! Could you please confirm that you have followed the Installation section from readme? If you didn't, please do that first. If you did, please provide more details, eg what is your OS, what version of Python are you running etc.

**Comment by Adryanvdb** [comment]
this happened to me too. i followed the installation on the readme (for as far as i can tell) and installed the dependencies manually according to this part of the guide: "Next, you have to install python dependencies: pip3 install "spotipy==2.16.1" "requests==2.23.0" and then restart Ulauncher." this didn't really change anything, even after logging out and in again and restarting Ulauncher. where can i find the crashlogs?

**Comment by Adryanvdb** [comment]
when starting from the terminal I get this (ignore the calculate-everything parts): 

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,636 | INFO | calculate_anything.units.parser: load_file() | Loaded unit definitions: /home/adryan/.local/share/ulauncher/extensions/com.github.tchar.ulauncher-albert-calculate-anything/data/lang/currency.txt
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,640 | INFO | calculate_anything.units.parser: load_file() | Loaded unit definitions: /home/adryan/.local/share/ulauncher/extensions/com.github.tchar.ulauncher-albert-calculate-anything/data/lang/units.txt
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,640 | INFO | calculate_anything.utils.misc: safe_operation() | CurrencyPreferences: set_currency_provider_protocol = http
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,640 | INFO | calculate_anything.currency.service: set_currency_provider_protocol() | Setting protocol = http
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,641 | INFO | calculate_anything.utils.misc: safe_operation() | CurrencyPreferences: add_provider = <calculate_anything.currency.providers.fixerio.FixerIOCurrencyProvider object at 0x7ccef97998b0>
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,641 | INFO | calculate_anything.currency.service: remove_provider() | Removing provider FixerIOCurrencyProvider
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,641 | INFO | calculate_anything.currency.service: add_provider() | Adding provider FixerIOCurrencyProvider
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,641 | INFO | calculate_anything.utils.misc: safe_operation() | CurrencyPreferences: cache_update_frequency = 86400
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,641 | INFO | calculate_anything.currency.service: enable_cache() | Enabling cache with update frequency = 86400
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,641 | INFO | calculate_anything.currency.cache: enable() | Enabling cache every 86400s
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,641 | INFO | calculate_anything.utils.misc: safe_operation() | CurrencyPreferences: default_currencies = ['USD', 'EUR', 'GBP', 'CAD']
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,641 | INFO | calculate_anything.currency.service: set_default_currencies() | Updating default currencies = ['USD', 'EUR', 'GBP', 'CAD']
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,641 | INFO | calculate_anything.currency.service: start() | Currency Service is running
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,642 | INFO | calculate_anything.currency.service.UpdateThread(id=2e50fe444d85): run() | Starting thread
com.github.tchar.ulauncher-albert-calculate-anything | 2025-05-05 17:32:12,645 | INFO | calculate_anything.units.service: _update_callback() | Updating currency registry
Traceback (most recent call last):
  File "/home/adryan/.local/share/ulauncher/extensions/com.github.the-lay.ulauncher-spotify-api/main.py", line 48, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adryan/.local/share/ulauncher/extensions/com.github.the-lay.ulauncher-spotify-api/main.py", line 69, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
2025-05-05 17:32:12,788 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.the-lay.ulauncher-spotify-api" was terminated with code 1

**Comment by Adryanvdb** [comment]
I got the same error when i tried to install the dependencies uding the command from the readme but I looked around and ended up using pipx instead, which worked. can I maybe change something in the main.py doc to make it work?
